{
 "title": "Python Troubleshooting",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"app:8000\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"app:8000\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "GC Collected Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(python_gc_objects_collected_total{instance=\"app:8000\"}[1m])",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "GC Uncollected Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(python_gc_objects_uncollectable_total{instance=\"app:8000\"}[1m])",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_requests_total{handler!=\"/metrics\",instance=\"app:8000\"}[1m])"
    }
   ]
  }
 ]
}