# Generated by Django 4.0.1 on 2022-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_timestamp', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=50)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tick',
            },
        ),
    ]
